/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 97
#define ALIAS_COUNT 0
#define TOKEN_COUNT 49
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LBRACE = 2,
  aux_sym_comment_token1 = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LPAREN = 5,
  anon_sym_COMMA = 6,
  anon_sym_RPAREN = 7,
  anon_sym_COLON = 8,
  anon_sym_DASH_GT = 9,
  anon_sym_Lexique = 10,
  anon_sym_lexique = 11,
  anon_sym_COLON_EQ = 12,
  anon_sym_Algorithme = 13,
  anon_sym_algorithme = 14,
  anon_sym_Debut = 15,
  anon_sym_Du00e9but = 16,
  anon_sym_debut = 17,
  anon_sym_du00e9but = 18,
  anon_sym_Start = 19,
  anon_sym_start = 20,
  anon_sym_Fin = 21,
  anon_sym_fin = 22,
  anon_sym_End = 23,
  anon_sym_end = 24,
  anon_sym_LT_DASH = 25,
  anon_sym_Retourner = 26,
  anon_sym_retourner = 27,
  anon_sym_Return = 28,
  anon_sym_return = 29,
  anon_sym_reel = 30,
  anon_sym_ru00e9el = 31,
  anon_sym_float = 32,
  anon_sym_int = 33,
  anon_sym_entier = 34,
  sym_string_type = 35,
  sym_void_type = 36,
  sym_bool_type = 37,
  sym_float = 38,
  sym_int = 39,
  anon_sym_DQUOTE = 40,
  aux_sym_string_token1 = 41,
  anon_sym_true = 42,
  anon_sym_false = 43,
  anon_sym_PLUS = 44,
  anon_sym_DASH = 45,
  anon_sym_STAR = 46,
  anon_sym_SLASH = 47,
  anon_sym_PERCENT = 48,
  sym_source_file = 49,
  sym__definition = 50,
  sym__expression = 51,
  sym_comment = 52,
  sym_func_definition = 53,
  sym_parameter_list = 54,
  sym_type_definition = 55,
  sym_output_type = 56,
  sym_vocabulary = 57,
  sym_vocab_keyword = 58,
  sym__declaration = 59,
  sym_var_declaration = 60,
  sym_const_declaration = 61,
  sym_const_assignation = 62,
  sym_func_declaration = 63,
  sym_parameter_type_list = 64,
  sym_algorithme = 65,
  sym_algorithme_keyword = 66,
  sym_algorithme_boundary = 67,
  sym_start_keyword = 68,
  sym_end_keyword = 69,
  sym_statement = 70,
  sym_assignation = 71,
  sym_return = 72,
  sym_return_keyword = 73,
  sym_func_call = 74,
  sym_parameter_input_list = 75,
  sym_type = 76,
  sym_primitive_type = 77,
  sym_float_type = 78,
  sym_int_type = 79,
  sym_primitive = 80,
  sym_string = 81,
  sym_bool = 82,
  sym__operation = 83,
  sym_add = 84,
  sym_sub = 85,
  sym_mul = 86,
  sym_div = 87,
  sym_reminder = 88,
  sym_minus = 89,
  sym_priority = 90,
  aux_sym_source_file_repeat1 = 91,
  aux_sym_parameter_list_repeat1 = 92,
  aux_sym_vocabulary_repeat1 = 93,
  aux_sym_parameter_type_list_repeat1 = 94,
  aux_sym_algorithme_boundary_repeat1 = 95,
  aux_sym_parameter_input_list_repeat1 = 96,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE] = "{",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_Lexique] = "Lexique",
  [anon_sym_lexique] = "lexique",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_Algorithme] = "Algorithme",
  [anon_sym_algorithme] = "algorithme",
  [anon_sym_Debut] = "Debut",
  [anon_sym_Du00e9but] = "D\u00e9but",
  [anon_sym_debut] = "debut",
  [anon_sym_du00e9but] = "d\u00e9but",
  [anon_sym_Start] = "Start",
  [anon_sym_start] = "start",
  [anon_sym_Fin] = "Fin",
  [anon_sym_fin] = "fin",
  [anon_sym_End] = "End",
  [anon_sym_end] = "end",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_Retourner] = "Retourner",
  [anon_sym_retourner] = "retourner",
  [anon_sym_Return] = "Return",
  [anon_sym_return] = "return",
  [anon_sym_reel] = "reel",
  [anon_sym_ru00e9el] = "r\u00e9el",
  [anon_sym_float] = "float",
  [anon_sym_int] = "int",
  [anon_sym_entier] = "entier",
  [sym_string_type] = "string_type",
  [sym_void_type] = "void_type",
  [sym_bool_type] = "bool_type",
  [sym_float] = "float",
  [sym_int] = "int",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__expression] = "_expression",
  [sym_comment] = "comment",
  [sym_func_definition] = "func_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_type_definition] = "type_definition",
  [sym_output_type] = "output_type",
  [sym_vocabulary] = "vocabulary",
  [sym_vocab_keyword] = "vocab_keyword",
  [sym__declaration] = "_declaration",
  [sym_var_declaration] = "var_declaration",
  [sym_const_declaration] = "const_declaration",
  [sym_const_assignation] = "const_assignation",
  [sym_func_declaration] = "func_declaration",
  [sym_parameter_type_list] = "parameter_type_list",
  [sym_algorithme] = "algorithme",
  [sym_algorithme_keyword] = "algorithme_keyword",
  [sym_algorithme_boundary] = "algorithme_boundary",
  [sym_start_keyword] = "start_keyword",
  [sym_end_keyword] = "end_keyword",
  [sym_statement] = "statement",
  [sym_assignation] = "assignation",
  [sym_return] = "return",
  [sym_return_keyword] = "return_keyword",
  [sym_func_call] = "func_call",
  [sym_parameter_input_list] = "parameter_input_list",
  [sym_type] = "type",
  [sym_primitive_type] = "primitive_type",
  [sym_float_type] = "float_type",
  [sym_int_type] = "int_type",
  [sym_primitive] = "primitive",
  [sym_string] = "string",
  [sym_bool] = "bool",
  [sym__operation] = "_operation",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_reminder] = "reminder",
  [sym_minus] = "minus",
  [sym_priority] = "priority",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_vocabulary_repeat1] = "vocabulary_repeat1",
  [aux_sym_parameter_type_list_repeat1] = "parameter_type_list_repeat1",
  [aux_sym_algorithme_boundary_repeat1] = "algorithme_boundary_repeat1",
  [aux_sym_parameter_input_list_repeat1] = "parameter_input_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_Lexique] = anon_sym_Lexique,
  [anon_sym_lexique] = anon_sym_lexique,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_Algorithme] = anon_sym_Algorithme,
  [anon_sym_algorithme] = anon_sym_algorithme,
  [anon_sym_Debut] = anon_sym_Debut,
  [anon_sym_Du00e9but] = anon_sym_Du00e9but,
  [anon_sym_debut] = anon_sym_debut,
  [anon_sym_du00e9but] = anon_sym_du00e9but,
  [anon_sym_Start] = anon_sym_Start,
  [anon_sym_start] = anon_sym_start,
  [anon_sym_Fin] = anon_sym_Fin,
  [anon_sym_fin] = anon_sym_fin,
  [anon_sym_End] = anon_sym_End,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_Retourner] = anon_sym_Retourner,
  [anon_sym_retourner] = anon_sym_retourner,
  [anon_sym_Return] = anon_sym_Return,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_reel] = anon_sym_reel,
  [anon_sym_ru00e9el] = anon_sym_ru00e9el,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_entier] = anon_sym_entier,
  [sym_string_type] = sym_string_type,
  [sym_void_type] = sym_void_type,
  [sym_bool_type] = sym_bool_type,
  [sym_float] = sym_float,
  [sym_int] = sym_int,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__expression] = sym__expression,
  [sym_comment] = sym_comment,
  [sym_func_definition] = sym_func_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_type_definition] = sym_type_definition,
  [sym_output_type] = sym_output_type,
  [sym_vocabulary] = sym_vocabulary,
  [sym_vocab_keyword] = sym_vocab_keyword,
  [sym__declaration] = sym__declaration,
  [sym_var_declaration] = sym_var_declaration,
  [sym_const_declaration] = sym_const_declaration,
  [sym_const_assignation] = sym_const_assignation,
  [sym_func_declaration] = sym_func_declaration,
  [sym_parameter_type_list] = sym_parameter_type_list,
  [sym_algorithme] = sym_algorithme,
  [sym_algorithme_keyword] = sym_algorithme_keyword,
  [sym_algorithme_boundary] = sym_algorithme_boundary,
  [sym_start_keyword] = sym_start_keyword,
  [sym_end_keyword] = sym_end_keyword,
  [sym_statement] = sym_statement,
  [sym_assignation] = sym_assignation,
  [sym_return] = sym_return,
  [sym_return_keyword] = sym_return_keyword,
  [sym_func_call] = sym_func_call,
  [sym_parameter_input_list] = sym_parameter_input_list,
  [sym_type] = sym_type,
  [sym_primitive_type] = sym_primitive_type,
  [sym_float_type] = sym_float_type,
  [sym_int_type] = sym_int_type,
  [sym_primitive] = sym_primitive,
  [sym_string] = sym_string,
  [sym_bool] = sym_bool,
  [sym__operation] = sym__operation,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_reminder] = sym_reminder,
  [sym_minus] = sym_minus,
  [sym_priority] = sym_priority,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_vocabulary_repeat1] = aux_sym_vocabulary_repeat1,
  [aux_sym_parameter_type_list_repeat1] = aux_sym_parameter_type_list_repeat1,
  [aux_sym_algorithme_boundary_repeat1] = aux_sym_algorithme_boundary_repeat1,
  [aux_sym_parameter_input_list_repeat1] = aux_sym_parameter_input_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Lexique] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lexique] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Algorithme] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_algorithme] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Debut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Du00e9but] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_debut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_du00e9but] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Start] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_start] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Fin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_End] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Retourner] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_retourner] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_reel] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ru00e9el] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entier] = {
    .visible = true,
    .named = false,
  },
  [sym_string_type] = {
    .visible = true,
    .named = true,
  },
  [sym_void_type] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_type] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_func_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_output_type] = {
    .visible = true,
    .named = true,
  },
  [sym_vocabulary] = {
    .visible = true,
    .named = true,
  },
  [sym_vocab_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_var_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_const_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_const_assignation] = {
    .visible = true,
    .named = true,
  },
  [sym_func_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_type_list] = {
    .visible = true,
    .named = true,
  },
  [sym_algorithme] = {
    .visible = true,
    .named = true,
  },
  [sym_algorithme_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_algorithme_boundary] = {
    .visible = true,
    .named = true,
  },
  [sym_start_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_end_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignation] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_return_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_func_call] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_input_list] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_float_type] = {
    .visible = true,
    .named = true,
  },
  [sym_int_type] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym__operation] = {
    .visible = false,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_reminder] = {
    .visible = true,
    .named = true,
  },
  [sym_minus] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_vocabulary_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_type_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_algorithme_boundary_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_input_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 40,
        '%', 48,
        '(', 27,
        ')', 29,
        '*', 46,
        '+', 43,
        ',', 28,
        '-', 45,
        '/', 47,
        ':', 31,
        '<', 2,
        'D', 22,
        'd', 24,
        'r', 23,
        '{', 16,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '{') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(32);
      END_STATE();
    case 5:
      if (lookahead == 'b') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 11:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 40,
        '%', 48,
        '(', 27,
        ')', 29,
        '*', 46,
        '+', 43,
        ',', 28,
        '-', 44,
        '/', 47,
        ':', 3,
        'D', 22,
        'd', 24,
        '{', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(42);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '{') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 0xe9) ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 0xe9) ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 0xe9) ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_Du00e9but);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_du00e9but);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_ru00e9el);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '{') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(32);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'A', 1,
        'D', 2,
        'E', 3,
        'F', 4,
        'L', 5,
        'R', 6,
        'S', 7,
        'a', 8,
        'b', 9,
        'd', 10,
        'e', 11,
        'f', 12,
        'i', 13,
        'l', 14,
        'r', 15,
        's', 16,
        't', 17,
        'v', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(30);
      if (lookahead == 'i') ADVANCE(31);
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 19:
      if (lookahead == 'g') ADVANCE(39);
      END_STATE();
    case 20:
      if (lookahead == 'b') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(41);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead == 'x') ADVANCE(43);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 26:
      if (lookahead == 'g') ADVANCE(46);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 28:
      if (lookahead == 'b') ADVANCE(48);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(49);
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 34:
      if (lookahead == 'x') ADVANCE(55);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(56);
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(58);
      if (lookahead == 'r') ADVANCE(59);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(60);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(63);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_End);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_Fin);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(65);
      if (lookahead == 'u') ADVANCE(66);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 48:
      if (lookahead == 'u') ADVANCE(70);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(71);
      END_STATE();
    case 51:
      if (lookahead == 's') ADVANCE(72);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_fin);
      END_STATE();
    case 53:
      if (lookahead == 'a') ADVANCE(73);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(74);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(75);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(76);
      if (lookahead == 'u') ADVANCE(77);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 59:
      if (lookahead == 'i') ADVANCE(79);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 61:
      if (lookahead == 'd') ADVANCE(81);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 64:
      if (lookahead == 'q') ADVANCE(84);
      END_STATE();
    case 65:
      if (lookahead == 'u') ADVANCE(85);
      END_STATE();
    case 66:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(87);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(88);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_bool_type);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(89);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(90);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 74:
      if (lookahead == 'q') ADVANCE(93);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_reel);
      END_STATE();
    case 76:
      if (lookahead == 'u') ADVANCE(94);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(95);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(96);
      END_STATE();
    case 79:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_void_type);
      END_STATE();
    case 82:
      if (lookahead == 'i') ADVANCE(98);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_Debut);
      END_STATE();
    case 84:
      if (lookahead == 'u') ADVANCE(99);
      END_STATE();
    case 85:
      if (lookahead == 'r') ADVANCE(100);
      END_STATE();
    case 86:
      if (lookahead == 'n') ADVANCE(101);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_Start);
      END_STATE();
    case 88:
      if (lookahead == 'i') ADVANCE(102);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_debut);
      END_STATE();
    case 90:
      if (lookahead == 'r') ADVANCE(103);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 93:
      if (lookahead == 'u') ADVANCE(104);
      END_STATE();
    case 94:
      if (lookahead == 'r') ADVANCE(105);
      END_STATE();
    case 95:
      if (lookahead == 'n') ADVANCE(106);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_start);
      END_STATE();
    case 97:
      if (lookahead == 'g') ADVANCE(107);
      END_STATE();
    case 98:
      if (lookahead == 't') ADVANCE(108);
      END_STATE();
    case 99:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 100:
      if (lookahead == 'n') ADVANCE(110);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_Return);
      END_STATE();
    case 102:
      if (lookahead == 't') ADVANCE(111);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_entier);
      END_STATE();
    case 104:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 105:
      if (lookahead == 'n') ADVANCE(113);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_string_type);
      END_STATE();
    case 108:
      if (lookahead == 'h') ADVANCE(114);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_Lexique);
      END_STATE();
    case 110:
      if (lookahead == 'e') ADVANCE(115);
      END_STATE();
    case 111:
      if (lookahead == 'h') ADVANCE(116);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_lexique);
      END_STATE();
    case 113:
      if (lookahead == 'e') ADVANCE(117);
      END_STATE();
    case 114:
      if (lookahead == 'm') ADVANCE(118);
      END_STATE();
    case 115:
      if (lookahead == 'r') ADVANCE(119);
      END_STATE();
    case 116:
      if (lookahead == 'm') ADVANCE(120);
      END_STATE();
    case 117:
      if (lookahead == 'r') ADVANCE(121);
      END_STATE();
    case 118:
      if (lookahead == 'e') ADVANCE(122);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_Retourner);
      END_STATE();
    case 120:
      if (lookahead == 'e') ADVANCE(123);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_retourner);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_Algorithme);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_algorithme);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 14},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 14},
  [28] = {.lex_state = 14},
  [29] = {.lex_state = 14},
  [30] = {.lex_state = 14},
  [31] = {.lex_state = 14},
  [32] = {.lex_state = 14},
  [33] = {.lex_state = 14},
  [34] = {.lex_state = 14},
  [35] = {.lex_state = 14},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 14},
  [41] = {.lex_state = 14},
  [42] = {.lex_state = 14},
  [43] = {.lex_state = 14},
  [44] = {.lex_state = 14},
  [45] = {.lex_state = 14},
  [46] = {.lex_state = 14},
  [47] = {.lex_state = 14},
  [48] = {.lex_state = 14},
  [49] = {.lex_state = 14},
  [50] = {.lex_state = 14},
  [51] = {.lex_state = 14},
  [52] = {.lex_state = 14},
  [53] = {.lex_state = 14},
  [54] = {.lex_state = 14},
  [55] = {.lex_state = 14},
  [56] = {.lex_state = 14},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 14},
  [59] = {.lex_state = 14},
  [60] = {.lex_state = 14},
  [61] = {.lex_state = 14},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 14},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 14},
  [69] = {.lex_state = 14},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 14},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 14},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 14},
  [78] = {.lex_state = 14},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 14},
  [86] = {.lex_state = 14},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 14},
  [91] = {.lex_state = 14},
  [92] = {.lex_state = 14},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 14},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 14},
  [97] = {.lex_state = 14},
  [98] = {.lex_state = 14},
  [99] = {.lex_state = 14},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 41},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 19},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(3),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_Lexique] = ACTIONS(1),
    [anon_sym_lexique] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_Algorithme] = ACTIONS(1),
    [anon_sym_algorithme] = ACTIONS(1),
    [anon_sym_Debut] = ACTIONS(1),
    [anon_sym_Du00e9but] = ACTIONS(1),
    [anon_sym_debut] = ACTIONS(1),
    [anon_sym_du00e9but] = ACTIONS(1),
    [anon_sym_Start] = ACTIONS(1),
    [anon_sym_start] = ACTIONS(1),
    [anon_sym_Fin] = ACTIONS(1),
    [anon_sym_fin] = ACTIONS(1),
    [anon_sym_End] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_Retourner] = ACTIONS(1),
    [anon_sym_retourner] = ACTIONS(1),
    [anon_sym_Return] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_reel] = ACTIONS(1),
    [anon_sym_ru00e9el] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_entier] = ACTIONS(1),
    [sym_string_type] = ACTIONS(1),
    [sym_void_type] = ACTIONS(1),
    [sym_bool_type] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(102),
    [sym__definition] = STATE(98),
    [sym_comment] = STATE(1),
    [sym_func_definition] = STATE(97),
    [aux_sym_source_file_repeat1] = STATE(58),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_RPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(2), 1,
      sym_comment,
    STATE(44), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [53] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(3), 1,
      sym_comment,
    STATE(19), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [103] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(4), 1,
      sym_comment,
    STATE(54), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [153] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(5), 1,
      sym_comment,
    STATE(35), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [203] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(6), 1,
      sym_comment,
    STATE(51), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [253] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(7), 1,
      sym_comment,
    STATE(33), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [303] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(8), 1,
      sym_comment,
    STATE(24), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [353] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(9), 1,
      sym_comment,
    STATE(56), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [403] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(10), 1,
      sym_comment,
    STATE(29), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [453] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(11), 1,
      sym_comment,
    STATE(28), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [503] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(12), 1,
      sym_comment,
    STATE(23), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [553] = 13,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      sym_float,
    ACTIONS(17), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(13), 1,
      sym_comment,
    STATE(22), 1,
      sym__expression,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym_string,
      sym_bool,
    STATE(16), 4,
      sym_func_call,
      sym_primitive,
      sym__operation,
      sym_priority,
    STATE(21), 6,
      sym_add,
      sym_sub,
      sym_mul,
      sym_div,
      sym_reminder,
      sym_minus,
  [603] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      sym_comment,
    STATE(20), 1,
      sym_parameter_input_list,
    ACTIONS(29), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(25), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [638] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_comment,
    ACTIONS(33), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(31), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [667] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym_comment,
    ACTIONS(29), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(25), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [696] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_comment,
    ACTIONS(37), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(35), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [725] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym_comment,
    ACTIONS(41), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(39), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [754] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_comment,
    ACTIONS(45), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(43), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [783] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_comment,
    ACTIONS(49), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(47), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [812] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_comment,
    ACTIONS(53), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(51), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [841] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_comment,
    ACTIONS(57), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [870] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(23), 1,
      sym_comment,
    ACTIONS(61), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(59), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [899] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_comment,
    ACTIONS(65), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(63), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [928] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(25), 1,
      sym_comment,
    ACTIONS(69), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(67), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [957] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_comment,
    ACTIONS(73), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(71), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [986] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_comment,
    ACTIONS(77), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(75), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1015] = 7,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_PERCENT,
    STATE(28), 1,
      sym_comment,
    ACTIONS(81), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(79), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1050] = 7,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_PERCENT,
    STATE(29), 1,
      sym_comment,
    ACTIONS(91), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1085] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(30), 1,
      sym_comment,
    ACTIONS(95), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(93), 11,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1114] = 10,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(97), 1,
      sym_identifier,
    STATE(5), 1,
      sym_return_keyword,
    STATE(31), 1,
      sym_comment,
    STATE(34), 1,
      aux_sym_algorithme_boundary_repeat1,
    STATE(42), 1,
      sym_statement,
    STATE(90), 1,
      sym_end_keyword,
    STATE(43), 2,
      sym_assignation,
      sym_return,
    ACTIONS(99), 4,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
    ACTIONS(101), 4,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1152] = 10,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(97), 1,
      sym_identifier,
    STATE(5), 1,
      sym_return_keyword,
    STATE(31), 1,
      aux_sym_algorithme_boundary_repeat1,
    STATE(32), 1,
      sym_comment,
    STATE(42), 1,
      sym_statement,
    STATE(85), 1,
      sym_end_keyword,
    STATE(43), 2,
      sym_assignation,
      sym_return,
    ACTIONS(99), 4,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
    ACTIONS(101), 4,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1190] = 8,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_PLUS,
    ACTIONS(107), 1,
      anon_sym_DASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(103), 9,
      sym_identifier,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1223] = 8,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(5), 1,
      sym_return_keyword,
    STATE(42), 1,
      sym_statement,
    STATE(34), 2,
      sym_comment,
      aux_sym_algorithme_boundary_repeat1,
    STATE(43), 2,
      sym_assignation,
      sym_return,
    ACTIONS(112), 4,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
    ACTIONS(114), 4,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1256] = 8,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_PLUS,
    ACTIONS(107), 1,
      anon_sym_DASH,
    STATE(35), 1,
      sym_comment,
    ACTIONS(117), 9,
      sym_identifier,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1289] = 9,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      sym_comment,
    STATE(53), 1,
      sym_primitive_type,
    STATE(82), 1,
      sym_type,
    ACTIONS(123), 2,
      anon_sym_int,
      anon_sym_entier,
    STATE(52), 2,
      sym_float_type,
      sym_int_type,
    ACTIONS(121), 3,
      anon_sym_reel,
      anon_sym_ru00e9el,
      anon_sym_float,
    ACTIONS(125), 3,
      sym_string_type,
      sym_void_type,
      sym_bool_type,
  [1323] = 8,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(37), 1,
      sym_comment,
    STATE(53), 1,
      sym_primitive_type,
    STATE(87), 1,
      sym_type,
    ACTIONS(123), 2,
      anon_sym_int,
      anon_sym_entier,
    STATE(52), 2,
      sym_float_type,
      sym_int_type,
    ACTIONS(121), 3,
      anon_sym_reel,
      anon_sym_ru00e9el,
      anon_sym_float,
    ACTIONS(125), 3,
      sym_string_type,
      sym_void_type,
      sym_bool_type,
  [1354] = 8,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_comment,
    STATE(53), 1,
      sym_primitive_type,
    STATE(59), 1,
      sym_type,
    ACTIONS(123), 2,
      anon_sym_int,
      anon_sym_entier,
    STATE(52), 2,
      sym_float_type,
      sym_int_type,
    ACTIONS(121), 3,
      anon_sym_reel,
      anon_sym_ru00e9el,
      anon_sym_float,
    ACTIONS(125), 3,
      sym_string_type,
      sym_void_type,
      sym_bool_type,
  [1385] = 8,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_comment,
    STATE(53), 1,
      sym_primitive_type,
    STATE(55), 1,
      sym_type,
    ACTIONS(123), 2,
      anon_sym_int,
      anon_sym_entier,
    STATE(52), 2,
      sym_float_type,
      sym_int_type,
    ACTIONS(121), 3,
      anon_sym_reel,
      anon_sym_ru00e9el,
      anon_sym_float,
    ACTIONS(125), 3,
      sym_string_type,
      sym_void_type,
      sym_bool_type,
  [1416] = 8,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 1,
      sym_identifier,
    STATE(32), 1,
      sym_start_keyword,
    STATE(40), 1,
      sym_comment,
    STATE(92), 1,
      sym_algorithme_boundary,
    ACTIONS(133), 2,
      anon_sym_Du00e9but,
      anon_sym_du00e9but,
    ACTIONS(131), 4,
      anon_sym_Debut,
      anon_sym_debut,
      anon_sym_Start,
      anon_sym_start,
  [1445] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_comment,
    ACTIONS(135), 9,
      sym_identifier,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1463] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym_comment,
    ACTIONS(137), 9,
      sym_identifier,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1481] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_comment,
    ACTIONS(139), 9,
      sym_identifier,
      anon_sym_Fin,
      anon_sym_fin,
      anon_sym_End,
      anon_sym_end,
      anon_sym_Retourner,
      anon_sym_retourner,
      anon_sym_Return,
      anon_sym_return,
  [1499] = 10,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_PLUS,
    ACTIONS(107), 1,
      anon_sym_DASH,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      sym_comment,
    STATE(84), 1,
      aux_sym_parameter_input_list_repeat1,
  [1530] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_comment,
    ACTIONS(147), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
    ACTIONS(145), 5,
      sym_identifier,
      anon_sym_Lexique,
      anon_sym_lexique,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1549] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_comment,
    ACTIONS(149), 4,
      sym_identifier,
      sym_int,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(151), 4,
      anon_sym_LPAREN,
      sym_float,
      anon_sym_DQUOTE,
      anon_sym_DASH,
  [1568] = 7,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(153), 1,
      sym_identifier,
    STATE(47), 1,
      sym_comment,
    STATE(49), 1,
      aux_sym_vocabulary_repeat1,
    STATE(77), 1,
      sym__declaration,
    ACTIONS(155), 2,
      anon_sym_Algorithme,
      anon_sym_algorithme,
    STATE(78), 3,
      sym_var_declaration,
      sym_const_declaration,
      sym_func_declaration,
  [1593] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_comment,
    ACTIONS(159), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
    ACTIONS(157), 5,
      sym_identifier,
      anon_sym_Lexique,
      anon_sym_lexique,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1612] = 7,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(153), 1,
      sym_identifier,
    STATE(49), 1,
      sym_comment,
    STATE(50), 1,
      aux_sym_vocabulary_repeat1,
    STATE(77), 1,
      sym__declaration,
    ACTIONS(161), 2,
      anon_sym_Algorithme,
      anon_sym_algorithme,
    STATE(78), 3,
      sym_var_declaration,
      sym_const_declaration,
      sym_func_declaration,
  [1637] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 1,
      sym_identifier,
    STATE(77), 1,
      sym__declaration,
    ACTIONS(166), 2,
      anon_sym_Algorithme,
      anon_sym_algorithme,
    STATE(50), 2,
      sym_comment,
      aux_sym_vocabulary_repeat1,
    STATE(78), 3,
      sym_var_declaration,
      sym_const_declaration,
      sym_func_declaration,
  [1660] = 8,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_PLUS,
    ACTIONS(107), 1,
      anon_sym_DASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(168), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1687] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_comment,
    ACTIONS(172), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
    ACTIONS(170), 5,
      sym_identifier,
      anon_sym_Lexique,
      anon_sym_lexique,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1706] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_comment,
    ACTIONS(176), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
    ACTIONS(174), 5,
      sym_identifier,
      anon_sym_Lexique,
      anon_sym_lexique,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1725] = 8,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_PLUS,
    ACTIONS(107), 1,
      anon_sym_DASH,
    STATE(54), 1,
      sym_comment,
    ACTIONS(178), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1751] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym_comment,
    ACTIONS(180), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
    ACTIONS(182), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_COLON_EQ,
  [1768] = 8,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_PLUS,
    ACTIONS(107), 1,
      anon_sym_DASH,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      sym_comment,
  [1793] = 7,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(186), 1,
      anon_sym_DASH_GT,
    STATE(57), 1,
      sym_comment,
    STATE(64), 1,
      sym_vocabulary,
    STATE(69), 1,
      sym_output_type,
    STATE(107), 1,
      sym_vocab_keyword,
    ACTIONS(188), 2,
      anon_sym_Lexique,
      anon_sym_lexique,
  [1816] = 7,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(190), 1,
      ts_builtin_sym_end,
    STATE(58), 1,
      sym_comment,
    STATE(61), 1,
      aux_sym_source_file_repeat1,
    STATE(97), 1,
      sym_func_definition,
    STATE(98), 1,
      sym__definition,
  [1838] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_comment,
    ACTIONS(192), 5,
      sym_identifier,
      anon_sym_Lexique,
      anon_sym_lexique,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1852] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(196), 1,
      anon_sym_COLON_EQ,
    STATE(60), 1,
      sym_comment,
    STATE(72), 1,
      sym_const_assignation,
    ACTIONS(194), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1870] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
    ACTIONS(200), 1,
      sym_identifier,
    STATE(97), 1,
      sym_func_definition,
    STATE(98), 1,
      sym__definition,
    STATE(61), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
  [1890] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(186), 1,
      anon_sym_DASH_GT,
    STATE(62), 1,
      sym_comment,
    STATE(74), 1,
      sym_output_type,
    ACTIONS(203), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1908] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(207), 1,
      anon_sym_DASH_GT,
    STATE(63), 1,
      sym_comment,
    ACTIONS(205), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1923] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_comment,
    STATE(86), 1,
      sym_algorithme,
    STATE(100), 1,
      sym_algorithme_keyword,
    ACTIONS(209), 2,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1940] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(213), 1,
      anon_sym_DASH_GT,
    STATE(65), 1,
      sym_comment,
    ACTIONS(211), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1955] = 6,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(215), 1,
      anon_sym_LPAREN,
    ACTIONS(217), 1,
      anon_sym_COLON,
    STATE(60), 1,
      sym_type_definition,
    STATE(62), 1,
      sym_parameter_type_list,
    STATE(66), 1,
      sym_comment,
  [1974] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(221), 1,
      anon_sym_DASH_GT,
    STATE(67), 1,
      sym_comment,
    ACTIONS(219), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [1989] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(68), 1,
      sym_comment,
    STATE(91), 1,
      sym_algorithme,
    STATE(100), 1,
      sym_algorithme_keyword,
    ACTIONS(209), 2,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [2006] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(68), 1,
      sym_vocabulary,
    STATE(69), 1,
      sym_comment,
    STATE(107), 1,
      sym_vocab_keyword,
    ACTIONS(188), 2,
      anon_sym_Lexique,
      anon_sym_lexique,
  [2023] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      sym_comment,
    STATE(76), 1,
      aux_sym_parameter_list_repeat1,
  [2039] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    STATE(71), 2,
      sym_comment,
      aux_sym_parameter_input_list_repeat1,
  [2053] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      sym_comment,
    ACTIONS(230), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [2065] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_comment,
    ACTIONS(232), 3,
      anon_sym_DASH_GT,
      anon_sym_Lexique,
      anon_sym_lexique,
  [2077] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(74), 1,
      sym_comment,
    ACTIONS(234), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [2089] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      sym_comment,
    STATE(83), 1,
      aux_sym_parameter_type_list_repeat1,
  [2105] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym_comment,
    STATE(80), 1,
      aux_sym_parameter_list_repeat1,
  [2121] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(77), 1,
      sym_comment,
    ACTIONS(242), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [2133] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(78), 1,
      sym_comment,
    ACTIONS(244), 3,
      sym_identifier,
      anon_sym_Algorithme,
      anon_sym_algorithme,
  [2145] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(79), 1,
      sym_comment,
    ACTIONS(246), 3,
      anon_sym_DASH_GT,
      anon_sym_Lexique,
      anon_sym_lexique,
  [2157] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(248), 1,
      anon_sym_COMMA,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    STATE(80), 2,
      sym_comment,
      aux_sym_parameter_list_repeat1,
  [2171] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(81), 1,
      sym_comment,
    ACTIONS(253), 3,
      anon_sym_DASH_GT,
      anon_sym_Lexique,
      anon_sym_lexique,
  [2183] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_parameter_type_list_repeat1,
    STATE(82), 1,
      sym_comment,
  [2199] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(257), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    STATE(83), 2,
      sym_comment,
      aux_sym_parameter_type_list_repeat1,
  [2213] = 5,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_parameter_input_list_repeat1,
    STATE(84), 1,
      sym_comment,
  [2229] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(85), 1,
      sym_comment,
    ACTIONS(264), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [2240] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(86), 1,
      sym_comment,
    ACTIONS(266), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [2251] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(87), 1,
      sym_comment,
    ACTIONS(260), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2262] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(217), 1,
      anon_sym_COLON,
    STATE(70), 1,
      sym_type_definition,
    STATE(88), 1,
      sym_comment,
  [2275] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(217), 1,
      anon_sym_COLON,
    STATE(89), 1,
      sym_comment,
    STATE(93), 1,
      sym_type_definition,
  [2288] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(90), 1,
      sym_comment,
    ACTIONS(268), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [2299] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(91), 1,
      sym_comment,
    ACTIONS(270), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [2310] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(92), 1,
      sym_comment,
    ACTIONS(272), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [2321] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(93), 1,
      sym_comment,
    ACTIONS(274), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2332] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(276), 1,
      sym_identifier,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      sym_comment,
  [2345] = 4,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(280), 1,
      anon_sym_LPAREN,
    STATE(57), 1,
      sym_parameter_list,
    STATE(95), 1,
      sym_comment,
  [2358] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(96), 1,
      sym_comment,
    ACTIONS(282), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [2369] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(97), 1,
      sym_comment,
    ACTIONS(284), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [2380] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    STATE(98), 1,
      sym_comment,
    ACTIONS(286), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [2391] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(288), 1,
      sym_identifier,
    STATE(99), 1,
      sym_comment,
  [2401] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(290), 1,
      anon_sym_COLON,
    STATE(100), 1,
      sym_comment,
  [2411] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    STATE(101), 1,
      sym_comment,
  [2421] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(294), 1,
      ts_builtin_sym_end,
    STATE(102), 1,
      sym_comment,
  [2431] = 3,
    ACTIONS(296), 1,
      anon_sym_LBRACE,
    ACTIONS(298), 1,
      aux_sym_string_token1,
    STATE(103), 1,
      sym_comment,
  [2441] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(300), 1,
      anon_sym_COLON,
    STATE(104), 1,
      sym_comment,
  [2451] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(302), 1,
      anon_sym_COLON,
    STATE(105), 1,
      sym_comment,
  [2461] = 3,
    ACTIONS(296), 1,
      anon_sym_LBRACE,
    ACTIONS(304), 1,
      aux_sym_comment_token1,
    STATE(106), 1,
      sym_comment,
  [2471] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(306), 1,
      anon_sym_COLON,
    STATE(107), 1,
      sym_comment,
  [2481] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(308), 1,
      anon_sym_LT_DASH,
    STATE(108), 1,
      sym_comment,
  [2491] = 3,
    ACTIONS(3), 1,
      anon_sym_LBRACE,
    ACTIONS(310), 1,
      anon_sym_DQUOTE,
    STATE(109), 1,
      sym_comment,
  [2501] = 1,
    ACTIONS(312), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 53,
  [SMALL_STATE(4)] = 103,
  [SMALL_STATE(5)] = 153,
  [SMALL_STATE(6)] = 203,
  [SMALL_STATE(7)] = 253,
  [SMALL_STATE(8)] = 303,
  [SMALL_STATE(9)] = 353,
  [SMALL_STATE(10)] = 403,
  [SMALL_STATE(11)] = 453,
  [SMALL_STATE(12)] = 503,
  [SMALL_STATE(13)] = 553,
  [SMALL_STATE(14)] = 603,
  [SMALL_STATE(15)] = 638,
  [SMALL_STATE(16)] = 667,
  [SMALL_STATE(17)] = 696,
  [SMALL_STATE(18)] = 725,
  [SMALL_STATE(19)] = 754,
  [SMALL_STATE(20)] = 783,
  [SMALL_STATE(21)] = 812,
  [SMALL_STATE(22)] = 841,
  [SMALL_STATE(23)] = 870,
  [SMALL_STATE(24)] = 899,
  [SMALL_STATE(25)] = 928,
  [SMALL_STATE(26)] = 957,
  [SMALL_STATE(27)] = 986,
  [SMALL_STATE(28)] = 1015,
  [SMALL_STATE(29)] = 1050,
  [SMALL_STATE(30)] = 1085,
  [SMALL_STATE(31)] = 1114,
  [SMALL_STATE(32)] = 1152,
  [SMALL_STATE(33)] = 1190,
  [SMALL_STATE(34)] = 1223,
  [SMALL_STATE(35)] = 1256,
  [SMALL_STATE(36)] = 1289,
  [SMALL_STATE(37)] = 1323,
  [SMALL_STATE(38)] = 1354,
  [SMALL_STATE(39)] = 1385,
  [SMALL_STATE(40)] = 1416,
  [SMALL_STATE(41)] = 1445,
  [SMALL_STATE(42)] = 1463,
  [SMALL_STATE(43)] = 1481,
  [SMALL_STATE(44)] = 1499,
  [SMALL_STATE(45)] = 1530,
  [SMALL_STATE(46)] = 1549,
  [SMALL_STATE(47)] = 1568,
  [SMALL_STATE(48)] = 1593,
  [SMALL_STATE(49)] = 1612,
  [SMALL_STATE(50)] = 1637,
  [SMALL_STATE(51)] = 1660,
  [SMALL_STATE(52)] = 1687,
  [SMALL_STATE(53)] = 1706,
  [SMALL_STATE(54)] = 1725,
  [SMALL_STATE(55)] = 1751,
  [SMALL_STATE(56)] = 1768,
  [SMALL_STATE(57)] = 1793,
  [SMALL_STATE(58)] = 1816,
  [SMALL_STATE(59)] = 1838,
  [SMALL_STATE(60)] = 1852,
  [SMALL_STATE(61)] = 1870,
  [SMALL_STATE(62)] = 1890,
  [SMALL_STATE(63)] = 1908,
  [SMALL_STATE(64)] = 1923,
  [SMALL_STATE(65)] = 1940,
  [SMALL_STATE(66)] = 1955,
  [SMALL_STATE(67)] = 1974,
  [SMALL_STATE(68)] = 1989,
  [SMALL_STATE(69)] = 2006,
  [SMALL_STATE(70)] = 2023,
  [SMALL_STATE(71)] = 2039,
  [SMALL_STATE(72)] = 2053,
  [SMALL_STATE(73)] = 2065,
  [SMALL_STATE(74)] = 2077,
  [SMALL_STATE(75)] = 2089,
  [SMALL_STATE(76)] = 2105,
  [SMALL_STATE(77)] = 2121,
  [SMALL_STATE(78)] = 2133,
  [SMALL_STATE(79)] = 2145,
  [SMALL_STATE(80)] = 2157,
  [SMALL_STATE(81)] = 2171,
  [SMALL_STATE(82)] = 2183,
  [SMALL_STATE(83)] = 2199,
  [SMALL_STATE(84)] = 2213,
  [SMALL_STATE(85)] = 2229,
  [SMALL_STATE(86)] = 2240,
  [SMALL_STATE(87)] = 2251,
  [SMALL_STATE(88)] = 2262,
  [SMALL_STATE(89)] = 2275,
  [SMALL_STATE(90)] = 2288,
  [SMALL_STATE(91)] = 2299,
  [SMALL_STATE(92)] = 2310,
  [SMALL_STATE(93)] = 2321,
  [SMALL_STATE(94)] = 2332,
  [SMALL_STATE(95)] = 2345,
  [SMALL_STATE(96)] = 2358,
  [SMALL_STATE(97)] = 2369,
  [SMALL_STATE(98)] = 2380,
  [SMALL_STATE(99)] = 2391,
  [SMALL_STATE(100)] = 2401,
  [SMALL_STATE(101)] = 2411,
  [SMALL_STATE(102)] = 2421,
  [SMALL_STATE(103)] = 2431,
  [SMALL_STATE(104)] = 2441,
  [SMALL_STATE(105)] = 2451,
  [SMALL_STATE(106)] = 2461,
  [SMALL_STATE(107)] = 2471,
  [SMALL_STATE(108)] = 2481,
  [SMALL_STATE(109)] = 2491,
  [SMALL_STATE(110)] = 2501,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_input_list, 4, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_input_list, 4, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_minus, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_minus, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_call, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__operation, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__operation, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reminder, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reminder, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_div, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_div, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_input_list, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_input_list, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_priority, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_priority, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_input_list, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_input_list, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignation, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_algorithme_boundary_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_algorithme_boundary_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_algorithme_boundary_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_algorithme, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_algorithme, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_keyword, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_algorithme_boundary_repeat1, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_type, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_type, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_keyword, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_keyword, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vocabulary, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_type, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_type, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vocabulary, 3, 0, 0),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_vocabulary_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_vocabulary_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_assignation, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_input_list_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_type, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_declaration, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_declaration, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_type_list, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type_list, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_type_list, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type_list, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_type_list, 4, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_type_list, 4, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_input_list_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_declaration, 3, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func_declaration, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_vocabulary_repeat1, 1, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 5, 0, 0),
  [248] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_type_list_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_type_list_repeat1, 2, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_algorithme_boundary, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_definition, 4, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_algorithme_boundary, 3, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_definition, 5, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_algorithme, 3, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 3, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_keyword, 1, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [294] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [296] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [298] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vocab_keyword, 1, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_algorithme_keyword, 1, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_algo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "algo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
